"""Read tools/assembly_config.json and regenerate the satellite-stage USDs.

Generates:
    usd/components.usda — /World/Satellite/LumidAssembly (full colored LUMID)
                          + /World/Cameras/Closeup
"""
from __future__ import annotations

import argparse
import asyncio
import json
import math
from pathlib import Path


ROOT            = Path("C:/Workspace/SpaceDC/space-compute-demo")
CONFIG          = ROOT / "tools" / "assembly_config.json"
COMPONENTS_USDA = ROOT / "usd"   / "components.usda"


def load_config() -> dict:
    return json.loads(CONFIG.read_text(encoding="utf-8"))


def save_config(cfg: dict) -> None:
    CONFIG.write_text(json.dumps(cfg, indent=2, ensure_ascii=False), encoding="utf-8")


def _lookat_matrix(eye, target):
    ex, ey, ez = eye; tx, ty, tz = target
    fx, fy, fz = tx - ex, ty - ey, tz - ez
    fn = math.sqrt(fx*fx + fy*fy + fz*fz) or 1.0
    fx, fy, fz = fx/fn, fy/fn, fz/fn
    rx, ry = fy, -fx
    rn = math.sqrt(rx*rx + ry*ry) or 1.0
    rx, ry = rx/rn, ry/rn
    ux = ry*fz; uy = -rx*fz; uz = rx*fy - ry*fx
    return [(rx, ry, 0.0, 0.0), (ux, uy, uz, 0.0), (-fx, -fy, -fz, 0.0), (ex, ey, ez, 1.0)]


def _fmt_tuple(v):
    return f"({', '.join(f'{float(x):.5f}' for x in v)})"


def generate_components(cfg: dict) -> str:
    lc = cfg["lumid"]
    lt = lc["translate"]; lr = lc["rotate"]; ls = lc["scale"]
    lumid_ref = lc["ref"].replace("\\", "/")

    cam = cfg["camera"]
    fl = float(cam["focal_length"])
    rows = _lookat_matrix(cam["eye"], cam["target"])

    L = [
        '#usda 1.0',
        '(',
        '    defaultPrim = "World"',
        '    upAxis = "Z"',
        '    metersPerUnit = 0.01',
        '    doc = "Satellite exterior — full colored LUMID model. Generated by tools/apply_assembly.py."',
        ')',
        '',
        'def Xform "World"',
        '{',
        '    def Xform "Satellite"',
        '    {',
        '        def Xform "LumidAssembly" (',
        f'            prepend references = @{lumid_ref}@',
        '        )',
        '        {',
        f'            double3 xformOp:translate = ({lt[0]}, {lt[1]}, {lt[2]})',
        f'            float3 xformOp:rotateXYZ = ({lr[0]}, {lr[1]}, {lr[2]})',
        f'            double3 xformOp:scale = ({ls[0]}, {ls[1]}, {ls[2]})',
        '            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]',
        '        }',
        '    }',
        '',
        '    def Xform "Cameras"',
        '    {',
        '        def Camera "Closeup"',
        '        {',
        f'            float focalLength = {fl}',
        '            float focusDistance = 300',
        '            float2 clippingRange = (1, 4000)',
        '            matrix4d xformOp:transform = (',
    ]
    for i, r in enumerate(rows):
        comma = "," if i < len(rows) - 1 else ""
        L.append(f'                {_fmt_tuple(r)}{comma}')
    L += [
        '            )',
        '            uniform token[] xformOpOrder = ["xformOp:transform"]',
        '        }',
        '    }',
        '}',
        '',
    ]
    return "\n".join(L)


async def reload_kit() -> None:
    import time as _time
    try:
        import websockets  # type: ignore
    except ImportError:
        print("[apply] websockets missing -- skipping Kit reload"); return
    try:
        async with websockets.connect("ws://localhost:8001/ws/state", open_timeout=10) as ws:
            await ws.send(json.dumps({"type": "change_camera", "ts": _time.time(), "payload": {"preset": "overview"}}))
            await asyncio.sleep(0.3)
            await ws.send(json.dumps({"type": "change_camera", "ts": _time.time(), "payload": {"preset": "satellite"}}))
            print("[apply] pinged backend -- Kit will reopen satellite stage")
    except Exception as e:
        print(f"[apply] Kit reload ping failed: {e}")


def apply(cfg=None, *, reload: bool = True) -> None:
    if cfg is None:
        cfg = load_config()
    COMPONENTS_USDA.write_text(generate_components(cfg), encoding="utf-8")
    print(f"[apply] wrote {COMPONENTS_USDA}")
    if reload:
        asyncio.run(reload_kit())


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--no-reload", action="store_true")
    args = p.parse_args()
    apply(reload=not args.no_reload)


if __name__ == "__main__":
    main()
