"""Generate usd/twin_satellite.usda — the Twin page's single-satellite body.

REBUILT 2026-06 around the SpaceDcBackbone.usdz spine. The previous body
(satellite_body.usdz bus + two solar.usdz wings + gold MLI override +
solar_material/solar_size variantSets) is gone — `delete all structures`.

The new structure is the backbone alone: a vertical spine carrying a thruster
module at each Z end, a central tank/wheel module, and FOUR quadrant racks
(±Y × upper/lower). Each rack is a stack of three open shelf-frames — twelve
server slots in total. This generator references the backbone and drops a
procedural compute-server blade into every slot so the satellite reads as a
populated orbital data center.

Geometry survey (tools/inspect_backbone.py + tools/analyze_slots.py):
    stage: Z-up, metersPerUnit 1.0, defaultPrim /root, bbox 0.18 × 0.45 × 1.0 m
    spine  : tripo_part_1   (Z beam)
    caps   : tripo_part_2 (+Z), tripo_part_8 (-Z)   thruster modules
    centre : tripo_part_6/7  (tank / reaction-wheel pack)
    racks  : tripo_part_0 (+Y up)  tripo_part_4 (-Y up)
             tripo_part_5 (+Y low) tripo_part_3 (-Y low)
    each rack: 3 frames; rails (area peaks) pair into 3 slot openings.

Host stage is metersPerUnit 0.01 (cm) — USD does not auto-convert units on a
reference, so the meters→cm framing scale lives on /World/Satellite. Servers
are authored in the backbone's native metre frame as children of that same
scaled Xform, so their coordinates line up 1:1 with the slot survey.

Preserved contracts (consumed by satellite.usda + space.demo.scene):
    /World                         defaultPrim, Z-up, cm
    /World/Satellite               body root (camera framing target)
    /World/Cameras/Closeup         bound camera (satellite.usda customLayerData)

Run:
    python tools/gen_twin_satellite.py
"""
from __future__ import annotations

import math
from pathlib import Path
from textwrap import indent

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT / "usd" / "twin_satellite.usda"

# Backbone: Z-up, metres, 1.0 m tall. ×180 frames it at 1.8 m in the cm host
# stage (matches the old body's ~1.7 m so the Closeup camera distances carry
# over). Authored on /World/Satellite so the servers inherit the same scale.
BACKBONE_REF   = "./assets/SpaceDcBackbone.usdz"
BACKBONE_SCALE = 180.0
# The backbone's 11 materials drive diffuse/metallic/roughness from grungy
# textures. Override each in place to clean shiny metal: constant clean colour,
# high metallic, low roughness, and BLOCK the dirty texture connections (the
# normal map is left connected for panel/bolt detail).
BACKBONE_MATS = ([f"tripo_part_{i}_material" for i in range(9)]
                 + ["tripo_part_new_0_material", "tripo_part_new_1_material"])
BACKBONE_DIFFUSE   = (0.620, 0.635, 0.660)     # clean neutral metal
BACKBONE_METALLIC  = 0.95
BACKBONE_ROUGHNESS = 0.18

# --- Server slots -----------------------------------------------------------
# Slot Z-centres are the mid-points of each frame's rail pair (the six area
# peaks per rack from analyze_slots.py group into three openings). Y is the
# cantilever mid of the rack arm; X is centred on the spine. All in backbone
# metres.
SLOT_Z_UPPER = (0.1165, 0.2075, 0.2980)
SLOT_Z_LOWER = (-0.1622, -0.2534, -0.3446)
SLOT_Y_ABS   = 0.135          # |Y| centre of the blade in the cantilever
# (name, y_sign, z-centres) — y_sign also flips the blade's front bezel side.
RACKS = [
    ("UpY", +1.0, SLOT_Z_UPPER),
    ("UnY", -1.0, SLOT_Z_UPPER),
    ("LpY", +1.0, SLOT_Z_LOWER),
    ("LnY", -1.0, SLOT_Z_LOWER),
]

# Blade box (backbone metres): X width, Y depth (cantilever), Z height. Sized
# to seat inside the ~0.045 m frame opening with margin and span most of the
# arm without colliding with the spine-side / tip-side posts.
BLADE_W = 0.130
BLADE_D = 0.155
BLADE_H = 0.034

# NVIDIA-style front-panel textures (generated by tools/gen_blade_texture.py) —
# used only by the procedural box blade when USE_DGX is False.
SERVER_FRONT_TEX      = "./textures/nv_blade_front.png"
SERVER_FRONT_EMIT_TEX = "./textures/nv_blade_front_emit.png"
SERVER_FRONT_EMIT     = (1.4, 1.4, 1.4)        # HDR scale so the green status dot blooms

# --- Real NVIDIA DGX A100 model in each rack slot -------------------------
# A local-only asset (~150 MB, references textures from a sibling Materials/
# tree), referenced in place by absolute path — triple-@ delimited because the
# folder name contains '@'. Each slot force-fits the DGX into the blade box:
# recenter → rotate (front +X out the rack opening ±Y, depth along Y) → non-
# uniform scale to BLADE_W×BLADE_D×BLADE_H → translate to the slot. instanceable
# so Kit shares one prototype across all 12.
USE_DGX    = True
DGX_REF    = ("C:/Users/markl/Downloads/Datacenter_NVD@10012/Assets/DigitalTwin/"
              "Assets/Datacenter/Server_Nodes/DGX/DGX_A100_01.usd")
DGX_CENTER = (-40.85, 24.12, 13.36)            # native bbox centre (cm)
DGX_SIZE   = (92.51, 48.26, 26.40)             # native size: X depth, Y width, Z height

# Server materials (UsdPreviewSurface).
SERVER_MATERIALS = {
    # Dark gunmetal chassis.
    "ServerChassis":  {"diffuse": (0.060, 0.065, 0.078), "metallic": 0.55,
                       "roughness": 0.50, "emissive": (0.010, 0.011, 0.014)},
    # Brushed-aluminium heat-spreader strip on top of each blade.
    "ServerHeatsink": {"diffuse": (0.560, 0.580, 0.610), "metallic": 0.80,
                       "roughness": 0.42, "emissive": (0.0, 0.0, 0.0)},
}

# --- Solar array ------------------------------------------------------------
# The backbone's mid-section deliberately carries no server racks: each ±Y face
# of the central module (tripo_part_6/7) instead presents a deployment bracket
# with a rotary hinge. A thin support boom reaches out from each bracket and
# carries oversized solar wings built from the real solar.usdz panel — far
# larger than the backbone itself — one wing per side.
#
# All lengths in backbone metres (the solar group is a child of the ×180
# /World/Satellite Xform, so 1 unit here = BACKBONE_SCALE cm = 1.8 m on stage).
SOLAR_REF    = "./assets/solar_panel_3d_model.usdz"
# Panel native (m): long 0.981 (X), wide 0.777 (Y), thick 0.054 (Z); the cell
# face is along ±Z. rotateY=90 stands the panel up: long→Z (wing height),
# wide→Y (deploy), and the cell normal Z→+X (the sun / camera side). The panels
# keep solar_panel_3d_model.usdz's own texture COLOUR — we only sharpen the
# finish in place (roughness 0.9→low, metallic up) so they reflect strongly.
SOLAR_NATIVE = (0.981, 0.777, 0.054)
SOLAR_MAT    = "tripo_mat_a4f32a50_bfaf_4ef6_a7aa_25f0c33672fc"  # asset's material
SOLAR_GLOSS_ROUGH = 0.08    # was 0.9 (very matte) → glossy
SOLAR_GLOSS_METAL = 0.95    # was 0.0 → strongly mirror-like, catches sun/earth reflections
PANEL_RY     = 90.0
# Per-panel scale (height, deploy, thickness) — non-uniform so the panel reads
# oversized and thin. Height 0.978×1.45≈1.42 (≈2.6 m on stage, taller than the
# 1.8 m body); deploy 0.666×1.05≈0.70; thickness 0.068×0.45≈0.031.
PANEL_SCALE  = (1.45, 1.05, 0.45)
N_PANELS     = 2          # two panel clusters chained into one wing per side
PANEL_GAP    = 0.0        # clusters abut — no gap between panels
# Each (formerly single) panel is a 2×2 grid of four smaller panels filling the
# same footprint. SUB_FRAC is each tile's per-axis scale vs the full panel;
# 0.5 makes the four tiles meet exactly edge-to-edge (no seam/gap).
SUB_FRAC     = 0.5

SOLAR_Z      = -0.024     # central-module hub height (boom + panel mid-Z)
SOLAR_X      = 0.030      # boom + panel plane, just off the +X spine face
BOOM_Y0      = 0.07       # boom root (seats inside the bracket)
BOOM_Y1      = 0.42       # boom tip / first-panel inner edge (clear of racks @0.227)
BOOM_THICK   = 0.012      # thin square support-rod cross-section (was 0.030)

# --- Radiator panels --------------------------------------------------------
# A boom off each ±Z end of the spine carries one long radiator. Its large-face
# normal is perpendicular to the solar panels' (solar faces +X; the radiator
# faces ±Y), and its SHORT edge meets the boom so the panel runs out along Z.
# rotateZ=90 then rotateX=90 maps the asset's native long-X → world Z (the long
# axis, up the boom), native wide-Y → world X (short edge), and the native +Z
# normal → world -Y. A single module (no tiling) scaled to a ~1:3 face with the
# thickness held (native-Z ×1).
RAD_REF        = "./assets/radiation_panel_3d_model.usdz"
RAD_NATIVE     = (0.9824, 0.6377, 0.0528)   # long X, wide Y, thick Z (normal Z)
# The radiator asset drives roughness/metallic from textures (can't be tuned in
# place), so each radiator mesh is rebound to a glossy specular RadiatorGlossy.
RAD_NODE       = "tripo_node_592ee2f8_9809_4148_9d8c_fd736a77b899"
RAD_MESH       = "tripo_mesh_592ee2f8_9809_4148_9d8c_fd736a77b899"
RAD_LONG       = 1.55     # world-Z length (backbone-m) — the long axis up the boom
RAD_RATIO      = 2.5      # short : long = 2 : 5
RAD_X          = 0.026    # centred on the spine axis
SPINE_END_Z    = 0.50     # spine ±Z ends (backbone bbox is Z ∈ [-0.5, 0.5])
RAD_BOOM_LEN   = 0.16     # boom reach along Z beyond the spine end
RAD_BOOM_THICK = 0.014    # thin square support rod

SOLAR_MATERIALS = {
    # Brushed-aluminium support boom (panels keep the asset's own materials).
    # Connecting boom + hinge pin — SAME clean shiny metal as the backbone
    # (identical colour + gloss), kept in sync via the BACKBONE_* constants.
    "SolarFrame": {"diffuse": BACKBONE_DIFFUSE, "metallic": BACKBONE_METALLIC,
                   "roughness": BACKBONE_ROUGHNESS, "emissive": (0.0, 0.0, 0.0)},
    "HingePinMetal": {"diffuse": BACKBONE_DIFFUSE, "metallic": BACKBONE_METALLIC,
                      "roughness": BACKBONE_ROUGHNESS, "emissive": (0.0, 0.0, 0.0)},
    # Glossy specular radiator finish (rebinds the texture-driven asset material
    # so the radiators reflect strongly) — bright OSR/quartz-mirror silver.
    "RadiatorGlossy": {"diffuse": (0.720, 0.745, 0.790), "metallic": 0.90,
                       "roughness": 0.06, "emissive": (0.0, 0.0, 0.0)},
}

# Dark photovoltaic blue for the PREVIEW_LITE box panels (the scanned solar
# usdz is ~1.9 M tris per tile — far too heavy for thumbnails). Kept OUT of
# SOLAR_MATERIALS: looks_scope() emits it only in lite mode, so the live
# no-arg output stays byte-identical to the historical generator.
LITE_MATERIALS = {
    "SolarCellLite": {"diffuse": (0.050, 0.095, 0.280), "metallic": 0.40,
                      "roughness": 0.30, "emissive": (0.004, 0.008, 0.024)},
}

# PREVIEW_LITE (twin_params.json key "preview_lite") swaps the two scanned
# multi-million-triangle deployable assets (solar tile / radiator panel) for
# same-footprint box meshes so tools/render_usd.py can rasterize a design
# thumbnail in seconds instead of minutes. The backbone reference stays — it
# is what makes the thumbnail recognizably *this* satellite. Never used for
# the live usd/twin_satellite.usda.
PREVIEW_LITE = False

# --- Satellite architectures -------------------------------------------------
# twin_params.json key "architecture" selects which HULL CONFIGURATION the
# generator builds — completely different satellite shapes, not just scaled
# wings (each design preset in backend/design_presets.py picks one):
#   truss      — single SpaceDcBackbone spine, 12 blades, 2×2-cluster side
#                wings, ±Z radiators (the classic orbital-DC look)
#   twin_truss — TWO backbones stacked into a 2-segment tower (24 blades),
#                wings mounted at the joint, radiators off the far ends
#   blanket    — single spine, but each wing is a long single-row blanket
#                (4 tiles per segment in a row) — an ISS-style ribbon wing
#   lumid      — the LUMID smallsat hull (integrated cross panels) + our
#                radiators; no external wings, GPUs ride inside the bus
#   dish       — the parabolic-dish comms hull with windmill wings + our
#                radiators; GPUs inside the bus
#   redwire    — the Redwire-style flat payload bay (GPUs inside the deck,
#                avionics module row on the +X face) + OUR generated solar
#                wings off the ±Y edges and ±Z boom radiators
ARCHITECTURES = ("truss", "twin_truss", "blanket", "lumid", "dish", "redwire")
ARCHITECTURE  = "truss"

LUMID_REF   = "./assets/LUMID_colored.usdc"
DISH_REF    = "./assets/Satellite_v022.usdc"
# Native bboxes (asset units — both were authored in mm):
#   LUMID:          2129 × 746 × 1919, cross panels in the X/Z plane
#   Satellite_v022:  106 × 168 × 168, dish axis along +X
# Both assets' pivots sit far from their bbox centers, so the hull prim must
# recenter (translate by −scale·center) or the radiator booms — placed
# assuming a centered hull — float in free space (~40-50 cm gaps).
LUMID_NATIVE_Z  = 1919.0
LUMID_NATIVE_CENTER = (112.4, 170.2, 114.0)
DISH_NATIVE_YZ  = 168.0
DISH_NATIVE_CENTER  = (-13.6, -5.1, 1.3)
# Hull scale targets, in backbone units (1 unit = BACKBONE_SCALE cm = 1.8 m):
LUMID_TARGET_U  = 3.1          # ≈ 5.6 m tall smallsat
DISH_TARGET_U   = 3.4          # ≈ 6.1 m across the windmill wings
# Radiator boom mount Z (backbone units) per hull — boom roots seat slightly
# inside the (recentered) hull envelope: LUMID half-height 1.55, dish 1.70.
LUMID_RAD_Z     = 1.50
DISH_RAD_Z      = 1.65

# Redwire payload bay: Z-up metres, bbox 0.938 × 1.000 × 0.247, pivot ~bbox
# centre in X/Y but 0.221 above it in Z (survey: scratchpad/inspect_redwire).
# tripo_part_9 is the flat deck; the other 7 parts are an avionics/module row
# along the native −Y edge. rotateZ=90 turns that row to face +X (the sun /
# camera side, next to the solar-cell plane) and leaves both ±Y edge faces
# clean for the wing yokes.
REDWIRE_REF     = "./assets/redwire_payload.usdz"
REDWIRE_NATIVE  = 1.0          # largest native dim (Y — becomes X after rot)
REDWIRE_NATIVE_CENTER = (0.0, 0.0, -0.2207)
REDWIRE_TARGET_U = 1.5         # deck ≈ 2.7 m across (compact bay, ~1/3 the
                               # volume of the first 2.2-u cut per user ref)
# The deck's native ±X edges (→ ±Y sides after rot90) each carry TWO
# protruding attachment lugs (survey scratchpad/find_tabs: native
# y ∈ [−0.36,−0.29] and [0.31,0.37], z ∈ [−0.20,−0.13], main plate edge at
# |x| ≈ 0.42, lug tips at 0.469). The solar wings bolt STRAIGHT onto those
# lugs: flat panels whose cell face is PARALLEL to the deck plane (+Z up —
# the asset's native orientation, no rotation at all), first cluster at the
# deck edge, growth chaining outward cluster by cluster.
REDWIRE_WING_Y0 = 0.71         # first panel inner edge ≈ deck edge (0.704)
REDWIRE_WING_Z  = 0.081        # lug mid-plane (native −0.167 recentred ×1.5)
REDWIRE_LUG_X   = (-0.50, 0.49)  # lug centres after rot90
# Radiator boom mount: deck half-Z = 0.124·1.5 ≈ 0.185, boom roots just inside.
REDWIRE_RAD_Z   = 0.17

# Closeup camera — a true 3/4 (from +X / -Y / above) so the solar wings (face
# +X) AND the perpendicular radiators (face ±Y, top/bottom) are both readable.
# Pulled far back to hold the full ~7.5 m span × ~5.5 m height.
CAM_EYE   = (1250.0, -1500.0, 1050.0)
CAM_FOCAL = 22.0

# --- Celestial context (Earth + Sun) ---------------------------------------
# In the twin view the Earth + Sun appear at realistic ANGULAR scale and
# position (literal 1:1 distances would wreck the depth buffer): the Earth fills
# ~64° below (the LEO horizon) and the Sun is a ~0.53° disk in the sun
# direction. Authored in absolute cm as siblings of the ×180 Satellite, so they
# sit at their true directions and sweep correctly as the camera orbits.
# Distances are compressed (literal 700 km would wreck the depth buffer) but the
# ANGULAR sizes are kept real: asin(R/D)=64° gives the true LEO Earth horizon,
# and the Sun spans the true ~0.53°. Earth surface sits ~2.5 m below the body.
EARTH_RADIUS_CM = 22_000.0                     # ~49° angular radius from the cam:
EARTH_CENTER    = (0.0, 0.0, -28_000.0)        # a big curved planet across the lower frame
EARTH_TEX       = "./textures/earth_day.jpg"
# Earth material stack (the ER0001 8K set): day diffuse (no emissive — the
# night side goes genuinely dark, per user preference); the ocean-specular
# mask inverted into roughness (sea glints under the swept Key sun, land
# stays matte); and a separate slightly-larger cloud sphere that rotates
# with the globe.
EARTH_SPEC_TEX   = "./textures/earth_spec.jpg"
CLOUD_TEX        = "./textures/earth_clouds.jpg"
CLOUD_SCALE      = 1.008               # cloud shell sits ~2.2 km up at scale
CLOUD_OPACITY    = 0.55                # airy — the ground must read through
SUN_TEX         = "./textures/sun_surface.png"
SUN_EMIT        = (12.0, 8.6, 3.4)             # HDR multiplier — with RTX bloom the ONE sun reads blinding
SUN_DIST_CM     = 50_000.0
SUN_RADIUS_CM   = 231.0                        # 50000·tan(0.265°) → ~0.53° disk
SUN_DIR         = (0.643, 0.0, 0.766)          # default Key sun source (+X / +Z)


# ---------------------------------------------------------------------------
def _c3(t: tuple[float, float, float]) -> str:
    return f"({t[0]:.3f}, {t[1]:.3f}, {t[2]:.3f})"


def material_block(name: str, p: dict) -> str:
    em = p.get("emissive", (0.0, 0.0, 0.0))
    return f"""
    def Material "{name}"
    {{
        token outputs:surface.connect = </World/Looks/{name}/Shader.outputs:surface>
        def Shader "Shader"
        {{
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor = {_c3(p['diffuse'])}
            color3f inputs:emissiveColor = {_c3(em)}
            float inputs:metallic = {p['metallic']:.3f}
            float inputs:roughness = {p['roughness']:.3f}
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }}
    }}"""


def textured_material(name: str, tex: str, metallic: float, roughness: float,
                      emissive: tuple[float, float, float]) -> str:
    """A diffuse-textured UsdPreviewSurface (UsdUVTexture ← st reader). Used for
    the photovoltaic panels and the equirectangular Earth."""
    return f"""
    def Material "{name}"
    {{
        token outputs:surface.connect = </World/Looks/{name}/Shader.outputs:surface>
        def Shader "Shader"
        {{
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor.connect = </World/Looks/{name}/Tex.outputs:rgb>
            color3f inputs:emissiveColor = {_c3(emissive)}
            float inputs:metallic = {metallic:.3f}
            float inputs:roughness = {roughness:.3f}
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }}
        def Shader "Tex"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{tex}@
            float2 inputs:st.connect = </World/Looks/{name}/St.outputs:result>
            token inputs:wrapS = "repeat"
            token inputs:wrapT = "repeat"
            float3 outputs:rgb
        }}
        def Shader "St"
        {{
            uniform token info:id = "UsdPrimvarReader_float2"
            token inputs:varname = "st"
            float2 outputs:result
        }}
    }}"""


def sun_material() -> str:
    """The Sun — a granulated solar-surface texture driving BOTH diffuse and
    (HDR-scaled) emissive, so the disk shows surface detail and glows like a
    star (with Kit bloom). UsdUVTexture inputs:scale lifts the 0..1 texture
    into HDR for the emissive path."""
    sc = SUN_EMIT
    return f"""
    def Material "SunMat"
    {{
        token outputs:surface.connect = </World/Looks/SunMat/Shader.outputs:surface>
        def Shader "Shader"
        {{
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor.connect = </World/Looks/SunMat/Tex.outputs:rgb>
            color3f inputs:emissiveColor.connect = </World/Looks/SunMat/Emit.outputs:rgb>
            float inputs:metallic = 0.0
            float inputs:roughness = 1.0
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }}
        def Shader "Tex"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{SUN_TEX}@
            float2 inputs:st.connect = </World/Looks/SunMat/St.outputs:result>
            float3 outputs:rgb
        }}
        def Shader "Emit"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{SUN_TEX}@
            float2 inputs:st.connect = </World/Looks/SunMat/St.outputs:result>
            float4 inputs:scale = ({sc[0]:.2f}, {sc[1]:.2f}, {sc[2]:.2f}, 1.0)
            float3 outputs:rgb
        }}
        def Shader "St"
        {{
            uniform token info:id = "UsdPrimvarReader_float2"
            token inputs:varname = "st"
            float2 outputs:result
        }}
    }}"""


def earth_material() -> str:
    """The ER0001 Earth: 8K day diffuse, NO emissive (the night side goes
    genuinely dark); the ocean-specular mask inverted into roughness via
    UsdUVTexture scale/bias (ocean spec=1 → roughness 0.2 sun-glint, land
    spec=0 → 0.95 matte)."""
    return f"""
    def Material "EarthMat"
    {{
        token outputs:surface.connect = </World/Looks/EarthMat/Shader.outputs:surface>
        def Shader "Shader"
        {{
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor.connect = </World/Looks/EarthMat/Day.outputs:rgb>
            float inputs:roughness.connect = </World/Looks/EarthMat/Rough.outputs:r>
            float inputs:metallic = 0.0
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }}
        def Shader "Day"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{EARTH_TEX}@
            float2 inputs:st.connect = </World/Looks/EarthMat/St.outputs:result>
            float3 outputs:rgb
        }}
        def Shader "Rough"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{EARTH_SPEC_TEX}@
            float2 inputs:st.connect = </World/Looks/EarthMat/St.outputs:result>
            float4 inputs:scale = (-0.75, -0.75, -0.75, 1.0)
            float4 inputs:bias = (0.95, 0.95, 0.95, 0.0)
            float outputs:r
        }}
        def Shader "St"
        {{
            uniform token info:id = "UsdPrimvarReader_float2"
            token inputs:varname = "st"
            float2 outputs:result
        }}
    }}"""


def cloud_material() -> str:
    """The cloud shell — white diffuse with the cloud map driving opacity
    (alpha blend), so the layer floats over the globe and the terminator
    shades it with the same Key light."""
    return f"""
    def Material "CloudMat"
    {{
        token outputs:surface.connect = </World/Looks/CloudMat/Shader.outputs:surface>
        def Shader "Shader"
        {{
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor = (1.0, 1.0, 1.0)
            float inputs:opacity.connect = </World/Looks/CloudMat/Tex.outputs:r>
            float inputs:opacityThreshold = 0.0
            float inputs:metallic = 0.0
            float inputs:roughness = 1.0
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }}
        def Shader "Tex"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{CLOUD_TEX}@
            float2 inputs:st.connect = </World/Looks/CloudMat/St.outputs:result>
            float4 inputs:scale = ({CLOUD_OPACITY:.2f}, {CLOUD_OPACITY:.2f}, {CLOUD_OPACITY:.2f}, 1.0)
            float outputs:r
        }}
        def Shader "St"
        {{
            uniform token info:id = "UsdPrimvarReader_float2"
            token inputs:varname = "st"
            float2 outputs:result
        }}
    }}"""


def server_front_material() -> str:
    """The NVIDIA blade front — diffuse from nv_blade_front.png + an HDR-scaled
    emissive from nv_blade_front_emit.png so the green status dot / brand glow
    survive eclipse. Matte-ish so the gold grille reads as anodized, not mirror."""
    e = SERVER_FRONT_EMIT
    return f"""
    def Material "ServerFront"
    {{
        token outputs:surface.connect = </World/Looks/ServerFront/Shader.outputs:surface>
        def Shader "Shader"
        {{
            uniform token info:id = "UsdPreviewSurface"
            color3f inputs:diffuseColor.connect = </World/Looks/ServerFront/Tex.outputs:rgb>
            color3f inputs:emissiveColor.connect = </World/Looks/ServerFront/Emit.outputs:rgb>
            float inputs:metallic = 0.0
            float inputs:roughness = 0.45
            int inputs:useSpecularWorkflow = 0
            token outputs:surface
        }}
        def Shader "Tex"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{SERVER_FRONT_TEX}@
            float2 inputs:st.connect = </World/Looks/ServerFront/St.outputs:result>
            float3 outputs:rgb
        }}
        def Shader "Emit"
        {{
            uniform token info:id = "UsdUVTexture"
            asset inputs:file = @{SERVER_FRONT_EMIT_TEX}@
            float2 inputs:st.connect = </World/Looks/ServerFront/St.outputs:result>
            float4 inputs:scale = ({e[0]:.2f}, {e[1]:.2f}, {e[2]:.2f}, 1.0)
            float3 outputs:rgb
        }}
        def Shader "St"
        {{
            uniform token info:id = "UsdPrimvarReader_float2"
            token inputs:varname = "st"
            float2 outputs:result
        }}
    }}"""


def looks_scope() -> str:
    blocks = [material_block(k, v) for k, v in SERVER_MATERIALS.items()]
    blocks.append(server_front_material())
    blocks += [material_block(k, v) for k, v in SOLAR_MATERIALS.items()]
    if PREVIEW_LITE:
        blocks += [material_block(k, v) for k, v in LITE_MATERIALS.items()]
    blocks.append(earth_material())
    blocks.append(cloud_material())
    blocks.append(sun_material())
    return f"""def Scope "Looks"
{{{''.join(blocks)}
}}"""


# 6 outward-wound quad faces for an axis-aligned box.
_BOX_FACES = ((0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
              (2, 3, 7, 6), (1, 2, 6, 5), (0, 4, 7, 3))


def box_mesh(name: str, cx: float, cy: float, cz: float,
             sx: float, sy: float, sz: float, material: str) -> str:
    """An axis-aligned box authored as an explicit Mesh so every renderer
    (Kit + tools/render_usd.py) draws it. doubleSided guards against any
    winding/backface surprises in the host viewport."""
    hx, hy, hz = sx / 2, sy / 2, sz / 2
    pts = [
        (cx - hx, cy - hy, cz - hz), (cx + hx, cy - hy, cz - hz),
        (cx + hx, cy + hy, cz - hz), (cx - hx, cy + hy, cz - hz),
        (cx - hx, cy - hy, cz + hz), (cx + hx, cy - hy, cz + hz),
        (cx + hx, cy + hy, cz + hz), (cx - hx, cy + hy, cz + hz),
    ]
    pstr = ", ".join(f"({p[0]:.5f}, {p[1]:.5f}, {p[2]:.5f})" for p in pts)
    idx  = ", ".join(str(i) for f in _BOX_FACES for i in f)
    return f"""def Mesh "{name}" (
    prepend apiSchemas = ["MaterialBindingAPI"]
)
{{
    uniform bool doubleSided = 1
    float3[] extent = [({cx-hx:.5f}, {cy-hy:.5f}, {cz-hz:.5f}), ({cx+hx:.5f}, {cy+hy:.5f}, {cz+hz:.5f})]
    int[] faceVertexCounts = [4, 4, 4, 4, 4, 4]
    int[] faceVertexIndices = [{idx}]
    point3f[] points = [{pstr}]
    uniform token subdivisionScheme = "none"
    rel material:binding = </World/Looks/{material}>
}}"""


def quad_mesh(name: str, cx: float, cy: float, cz: float, sx: float, sz: float,
              y_normal: float, material: str) -> str:
    """A single textured quad in the X-Z plane facing ±Y (y_normal=±1), with 0..1
    UVs (U=+X across width, V=+Z up). Wound CCW toward its own outward side so the
    texture isn't mirrored on the −Y racks. box_mesh has no UVs, so textured
    panels use this."""
    hx, hz = sx / 2, sz / 2
    if y_normal > 0:
        pts = [(cx-hx, cy, cz-hz), (cx+hx, cy, cz-hz), (cx+hx, cy, cz+hz), (cx-hx, cy, cz+hz)]
    else:
        pts = [(cx+hx, cy, cz-hz), (cx-hx, cy, cz-hz), (cx-hx, cy, cz+hz), (cx+hx, cy, cz+hz)]
    sts = [(0, 0), (1, 0), (1, 1), (0, 1)]
    pstr = ", ".join(f"({p[0]:.5f}, {p[1]:.5f}, {p[2]:.5f})" for p in pts)
    ststr = ", ".join(f"({s[0]:.3f}, {s[1]:.3f})" for s in sts)
    return f"""def Mesh "{name}" (
    prepend apiSchemas = ["MaterialBindingAPI"]
)
{{
    uniform bool doubleSided = 1
    int[] faceVertexCounts = [4]
    int[] faceVertexIndices = [0, 1, 2, 3]
    point3f[] points = [{pstr}]
    texCoord2f[] primvars:st = [{ststr}] (interpolation = "vertex")
    uniform token subdivisionScheme = "none"
    rel material:binding = </World/Looks/{material}>
}}"""


def server_blade(name: str, cx: float, cy: float, cz: float, y_sign: float) -> str:
    """One NVIDIA-style compute blade: dark chassis + a textured DGX front panel
    (gold chevron grille + NVIDIA-green brand rail) recessed inside a brushed-alu
    bezel frame with rack ears, plus the heat-spreader strip on top. The front
    faces out of the rack opening (y_sign) toward deep space."""
    fy = cy + y_sign * (BLADE_D / 2 + 0.001)        # textured panel, just proud
    fy0 = cy + y_sign * (BLADE_D / 2 - 0.003)       # bezel frame plane
    ey = cy + y_sign * (BLADE_D / 2)                # rack ears at the front edge
    HK = "ServerHeatsink"
    parts = [
        box_mesh("Chassis", cx, cy, cz, BLADE_W, BLADE_D, BLADE_H, "ServerChassis"),
        quad_mesh("Front", cx, fy, cz, BLADE_W, BLADE_H, y_sign, "ServerFront"),
        box_mesh("Heatsink", cx, cy, cz + BLADE_H / 2, BLADE_W * 0.70,
                 BLADE_D * 0.86, 0.006, HK),
        # recessed bezel frame around the panel (silhouette detail)
        box_mesh("FrameTop", cx, fy0, cz + (BLADE_H / 2 - 0.002), BLADE_W, 0.006, 0.004, HK),
        box_mesh("FrameBot", cx, fy0, cz - (BLADE_H / 2 - 0.002), BLADE_W, 0.006, 0.004, HK),
        box_mesh("FramePostL", cx - (BLADE_W / 2 - 0.0025), fy0, cz, 0.005, 0.006, BLADE_H, HK),
        box_mesh("FramePostR", cx + (BLADE_W / 2 - 0.0025), fy0, cz, 0.005, 0.006, BLADE_H, HK),
        # rack mounting ears
        box_mesh("EarL", cx - (BLADE_W / 2 + 0.005), ey, cz, 0.010, 0.012, BLADE_H * 0.7, HK),
        box_mesh("EarR", cx + (BLADE_W / 2 + 0.005), ey, cz, 0.010, 0.012, BLADE_H * 0.7, HK),
    ]
    body = "\n".join(parts)
    return f'def Xform "{name}"\n{{\n{indent(body, "    ")}\n}}'


def _mat_id():
    return [[1.0 if i == j else 0.0 for j in range(4)] for i in range(4)]


def _mat_mul(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(4)) for j in range(4)] for i in range(4)]


def _T(tx, ty, tz):
    m = _mat_id(); m[3][0], m[3][1], m[3][2] = tx, ty, tz; return m


def _S(sx, sy, sz):
    m = _mat_id(); m[0][0], m[1][1], m[2][2] = sx, sy, sz; return m


def _Rz(deg):
    c, s = math.cos(math.radians(deg)), math.sin(math.radians(deg))
    m = _mat_id(); m[0][0], m[0][1], m[1][0], m[1][1] = c, s, -s, c; return m


def dgx_blade(name: str, cx: float, cy: float, cz: float, y_sign: float) -> str:
    """One real DGX A100, force-fit into the blade box. Row-vector transform:
    recenter (native cm) → rotateZ (front +X → outward ±Y, depth along Y) →
    non-uniform scale (cm → backbone units, fills BLADE_W×BLADE_D×BLADE_H) →
    translate to the slot. Referenced in place (absolute path) + instanceable."""
    Cx, Cy, Cz = DGX_CENTER
    dX, dY, dZ = DGX_SIZE                       # X depth, Y width, Z height
    sx = BLADE_W / dY                           # native Y (width)  → world X
    sy = BLADE_D / dX                           # native X (depth)  → world Y
    sz = BLADE_H / dZ                           # native Z (height) → world Z
    ang = 90.0 if y_sign > 0 else -90.0         # front +X faces y_sign·Y (out the slot)
    M = _mat_mul(_mat_mul(_mat_mul(_T(-Cx, -Cy, -Cz), _Rz(ang)), _S(sx, sy, sz)),
                 _T(cx, cy, cz))
    rows = ", ".join("(" + ", ".join(f"{v:.8f}" for v in r) + ")" for r in M)
    return (
        f'def Xform "{name}" (\n'
        f'    prepend references = @@@{DGX_REF}@@@\n'
        f'    instanceable = true\n'
        f')\n'
        f'{{\n'
        f'    matrix4d xformOp:transform = ({rows})\n'
        f'    uniform token[] xformOpOrder = ["xformOp:transform"]\n'
        f'}}'
    )


def servers_group(z_off: float = 0.0, tag: str = "") -> str:
    """The 12 blades of one backbone segment. `z_off`/`tag` let twin_truss
    stack a second segment's worth (Server_<rack>_<i>U / ...D)."""
    make = dgx_blade if USE_DGX else server_blade
    blades = []
    for rack_name, y_sign, zs in RACKS:
        cy = y_sign * SLOT_Y_ABS
        for i, cz in enumerate(zs):
            blades.append(make(f"Server_{rack_name}_{i}{tag}", 0.0, cy, cz + z_off, y_sign))
    body = "\n".join(blades)
    name = f"Servers{tag}" if tag else "Servers"
    return f'def Xform "{name}"\n{{\n{indent(body, "    ")}\n}}'


def deployable_prototypes(include_solar: bool = True) -> str:
    """Shared prototypes for the instanced deployables (full-asset mode only).

    Every solar tile / radiator panel used to carry its own reference to the
    ~1.9 M-triangle scanned usdz — 40-64 independent composition arcs that Kit
    had to load one by one (the main cause of slow satellite-stage loads).
    Instead we author ONE `class` prototype per asset (abstract → never
    rendered/traversed itself) holding the asset reference + shared material
    overrides, and each placement is an `instanceable` internal reference.
    Kit then composes each usdz once and instances it on the GPU.

    Transforms stay on each instance root: local opinions there
    (xformOpOrder) would mask any prototype-side ops, so authoring them in
    one place — the instance — is the only non-brittle split.

    `include_solar=False` (hull architectures — lumid/dish carry their own
    integrated panels) skips the SolarTile prototype entirely: even an
    abstract class prim composes its reference arcs, so emitting it would
    make Kit load the 78 MB tile asset for nothing."""
    solar_proto = (
        f'    def Xform "SolarTile" (\n'
        f'        prepend references = @{SOLAR_REF}@\n'
        f'    )\n'
        f'    {{\n'
        f'        over "_materials"\n'
        f'        {{\n'
        f'            over "{SOLAR_MAT}"\n'
        f'            {{\n'
        f'                over "Principled_BSDF"\n'
        f'                {{\n'
        f'                    float inputs:roughness = {SOLAR_GLOSS_ROUGH}\n'
        f'                    float inputs:metallic = {SOLAR_GLOSS_METAL}\n'
        f'                }}\n'
        f'            }}\n'
        f'        }}\n'
        f'    }}\n'
        f'\n'
    ) if include_solar else ''
    return (
        f'class Xform "_Protos"\n'
        f'{{\n'
        f'{solar_proto}'
        f'    def Xform "RadiatorPanel" (\n'
        f'        prepend references = @{RAD_REF}@\n'
        f'    )\n'
        f'    {{\n'
        f'        over "{RAD_NODE}"\n'
        f'        {{\n'
        f'            over "{RAD_MESH}"\n'
        f'            {{\n'
        f'                rel material:binding = </World/Looks/RadiatorGlossy>\n'
        f'            }}\n'
        f'        }}\n'
        f'    }}\n'
        f'}}'
    )


def solar_panel(name: str, cx: float, cy: float, cz: float,
                scale: tuple[float, float, float],
                flat: bool = False) -> str:
    """One solar tile. Full-asset mode: an instanceable internal reference to
    the shared /World/Satellite/_Protos/SolarTile prototype (rotate/scale/
    material live there) carrying only this tile's translate. Lite mode: a
    12-tri box with the same world footprint for the software previews.

    Upright (default): rotateY stands the panel up — long axis → world Z,
    cell normal → +X (the truss/blanket wing walls). `flat`: NO rotation at
    all — the asset's native pose already lies cell-face +Z with the long
    axis along X, which is exactly the redwire deck-parallel orientation."""
    sx, sy, sz = scale
    if PREVIEW_LITE:
        # Same world-space footprint as the (possibly rotated) scaled asset
        # as a 12-tri box instead of a 1.9 M-tri scan. Upright: native X →
        # world Z (height), native Y → world Y (deploy), thickness → X.
        # Flat: native axes ARE world axes (long X, wide Y, thin Z).
        if flat:
            return box_mesh(name, cx, cy, cz,
                            SOLAR_NATIVE[0] * sx, SOLAR_NATIVE[1] * sy,
                            SOLAR_NATIVE[2] * sz, "SolarCellLite")
        return box_mesh(name, cx, cy, cz,
                        SOLAR_NATIVE[2] * sz, SOLAR_NATIVE[1] * sy,
                        SOLAR_NATIVE[0] * sx, "SolarCellLite")
    rot = '' if flat else f'    float xformOp:rotateY = {PANEL_RY}\n'
    order = ('["xformOp:translate", "xformOp:scale"]' if flat
             else '["xformOp:translate", "xformOp:rotateY", "xformOp:scale"]')
    return (
        f'def Xform "{name}" (\n'
        f'    instanceable = true\n'
        f'    prepend references = </World/Satellite/_Protos/SolarTile>\n'
        f')\n'
        f'{{\n'
        f'    double3 xformOp:translate = ({cx:.4f}, {cy:.4f}, {cz:.4f})\n'
        f'{rot}'
        f'    double3 xformOp:scale = ({sx:.4f}, {sy:.4f}, {sz:.4f})\n'
        f'    uniform token[] xformOpOrder = {order}\n'
        f'}}'
    )


def solar_cluster(prefix: str, cx: float, cy: float, cz: float,
                  flat: bool = False) -> list[str]:
    """A 2×2 grid of four small panels filling one full-panel footprint.
    Upright: the big panel spans H (along Z) × D (along Y). Flat (redwire,
    deck-parallel): H runs along X (across the bay) and D along Y (the
    deploy direction), tiles in the X-Y plane — total cell area is
    identical either way (the physics area formula doesn't care about
    orientation)."""
    H = SOLAR_NATIVE[0] * PANEL_SCALE[0]      # full-panel long axis
    D = SOLAR_NATIVE[1] * PANEL_SCALE[1]      # full-panel deploy axis
    sub = (PANEL_SCALE[0] * SUB_FRAC, PANEL_SCALE[1] * SUB_FRAC, PANEL_SCALE[2])
    tiles = []
    if flat:
        for r, xs in enumerate((-1.0, 1.0)):      # two columns (X, across)
            for c, ys in enumerate((-1.0, 1.0)):  # two rows (Y, outward)
                tiles.append(solar_panel(f"{prefix}_{r}{c}",
                                         cx + xs * H / 4.0, cy + ys * D / 4.0,
                                         cz, sub, flat=True))
        return tiles
    for r, zs in enumerate((1.0, -1.0)):          # two rows (Z)
        for c, ys in enumerate((-1.0, 1.0)):      # two columns (Y)
            tiles.append(solar_panel(f"{prefix}_{r}{c}",
                                     cx, cy + ys * D / 4.0, cz + zs * H / 4.0,
                                     sub))
    return tiles


def solar_wing(side: float) -> str:
    """One deployed solar wing: a thin support boom from the central bracket
    out along `side`·Y, carrying N_PANELS chained panel clusters. Each cluster
    is a 2×2 grid of four small panels, standing upright with the cell face
    toward +X (sun side) on both wings."""
    s = side
    deploy = SOLAR_NATIVE[1] * PANEL_SCALE[1]          # per-cluster span along Y
    X, Z = SOLAR_X, SOLAR_Z
    r = 0.0
    # Tapered deployment yoke: root bracket → hinge clevis + bright pin →
    # 3-segment stepped taper → tip fork gripping the first panel. Reads as an
    # engineered cantilever instead of a crude rod.
    parts = [
        box_mesh("YokeBracket",  X, (r + 0.085) * s, Z, 0.026, 0.060, 0.052, "SolarFrame"),
        box_mesh("HingeClevisA", X, (r + 0.130) * s, -0.004, 0.020, 0.034, 0.014, "SolarFrame"),
        box_mesh("HingeClevisB", X, (r + 0.130) * s, -0.044, 0.020, 0.034, 0.014, "SolarFrame"),
        box_mesh("HingePin",     X, (r + 0.130) * s, Z, 0.010, 0.012, 0.058, "HingePinMetal"),
        box_mesh("ArmSeg1",      X, (r + 0.190) * s, Z, 0.018, 0.086, 0.034, "SolarFrame"),
        box_mesh("ArmSeg2",      X, (r + 0.270) * s, Z, 0.014, 0.074, 0.026, "SolarFrame"),
        box_mesh("ArmSeg3",      X, (r + 0.347) * s, Z, 0.010, 0.080, 0.018, "SolarFrame"),
        box_mesh("TipForkA",     X, (r + 0.405) * s, -0.012, 0.012, 0.040, 0.010, "SolarFrame"),
        box_mesh("TipForkB",     X, (r + 0.405) * s, -0.036, 0.012, 0.040, 0.010, "SolarFrame"),
    ]
    for i in range(N_PANELS):
        cy = (r + BOOM_Y1 + deploy / 2.0 + i * (deploy + PANEL_GAP)) * s
        parts.extend(solar_cluster(f"Cluster{i}", SOLAR_X, cy, SOLAR_Z))
    name = "WingPosY" if side > 0 else "WingNegY"
    body = "\n".join(parts)
    return f'def Xform "{name}"\n{{\n{indent(body, "    ")}\n}}'


def blanket_wing(side: float) -> str:
    """ISS-style ribbon wing (the `blanket` architecture): each segment is a
    single ROW of four tiles (1 tall × 4 wide along the deploy axis) instead
    of the truss wings' 2×2 stack, so the wing reads as a long thin blanket.
    Tile count per segment matches a truss cluster (4), so the physics area
    formula (clusters × 2 × cluster-area) is IDENTICAL across both archs."""
    s = side
    H = SOLAR_NATIVE[0] * PANEL_SCALE[0]          # full-cluster height along Z
    D = SOLAR_NATIVE[1] * PANEL_SCALE[1]          # full-cluster deploy along Y
    sub = (PANEL_SCALE[0] * SUB_FRAC, PANEL_SCALE[1] * SUB_FRAC, PANEL_SCALE[2])
    X = SOLAR_X
    # Blanket rides the truss mid-line (Z = 0) so the ribbon reads symmetric.
    Z = 0.0
    parts = [
        box_mesh("YokeBracket",  X, 0.085 * s, Z, 0.026, 0.060, 0.052, "SolarFrame"),
        box_mesh("HingePin",     X, 0.130 * s, Z, 0.010, 0.012, 0.058, "HingePinMetal"),
        box_mesh("ArmSeg1",      X, 0.190 * s, Z, 0.018, 0.086, 0.034, "SolarFrame"),
        box_mesh("ArmSeg2",      X, 0.290 * s, Z, 0.014, 0.074, 0.026, "SolarFrame"),
        box_mesh("ArmSeg3",      X, 0.380 * s, Z, 0.010, 0.080, 0.018, "SolarFrame"),
    ]
    # One segment = 4 tiles side by side along Y; segments chain outward.
    seg_span = 4 * (D / 2.0)                       # 4 half-cluster-wide tiles
    for i in range(N_PANELS):
        seg_y0 = BOOM_Y1 + i * seg_span
        for c in range(4):
            cy = (seg_y0 + (c + 0.5) * (D / 2.0)) * s
            parts.append(solar_panel(f"Cluster{i}_{c}", X, cy, Z, sub))
    name = "WingPosY" if side > 0 else "WingNegY"
    body = "\n".join(parts)
    return f'def Xform "{name}"\n{{\n{indent(body, "    ")}\n}}'


def redwire_wing(side: float) -> str:
    """Redwire flat wing: panel face PARALLEL to the deck plane (cells +Z),
    bolted STRAIGHT onto the deck's two edge lugs — no boom, no yoke. Two
    small hinge plates bridge the lug tips (x ≈ ±0.5, the deck edge at
    y ≈ 0.70) to the first cluster's inner edge; each extra cluster chains
    outward along Y by its D span, so growing the wing visibly adds panels
    one after another off the bay edge."""
    s = side
    H = SOLAR_NATIVE[0] * PANEL_SCALE[0]      # cluster span across X (1.42)
    D = SOLAR_NATIVE[1] * PANEL_SCALE[1]      # cluster span outward Y (0.816)
    Z = REDWIRE_WING_Z
    parts = [
        box_mesh(f"Hinge{'A' if lx < 0 else 'B'}",
                 lx, (REDWIRE_WING_Y0 + 0.005) * s, Z,
                 0.12, 0.15, 0.026, "SolarFrame")
        for lx in REDWIRE_LUG_X
    ]
    for i in range(N_PANELS):
        cy = (REDWIRE_WING_Y0 + D / 2.0 + i * (D + PANEL_GAP)) * s
        parts.extend(solar_cluster(f"Cluster{i}", 0.0, cy, Z, flat=True))
    name = "WingPosY" if side > 0 else "WingNegY"
    body = "\n".join(parts)
    return f'def Xform "{name}"\n{{\n{indent(body, "    ")}\n}}'


def solar_group() -> str:
    if ARCHITECTURE == "blanket":
        wing = blanket_wing
    elif ARCHITECTURE == "redwire":
        wing = redwire_wing
    else:
        wing = solar_wing
    body = wing(1.0) + "\n" + wing(-1.0)
    return f'def Xform "SolarArray"\n{{\n{indent(body, "    ")}\n}}'


def radiator_panel(name: str, cx: float, cy: float, cz: float) -> str:
    """One radiation_panel_3d_model.usdz panel: rotateZ=90 then rotateX=90 so
    the native long-X runs along world Z (the long axis), native wide-Y along
    world X (short edge), and the +Z normal → world -Y (⊥ solar +X). Scaled to
    a ~1:3 face with thickness held (native-Z ×1). Ops apply scale, rotateZ,
    rotateX, then translate. The mesh is rebound to the glossy RadiatorGlossy
    so it reflects strongly (its asset roughness/metallic are texture-driven and
    can't be tuned in place)."""
    short_x = RAD_LONG / RAD_RATIO                # world X extent (short edge)
    if PREVIEW_LITE:
        # Long axis up world Z, short edge along X, native thickness along Y.
        return box_mesh(name, cx, cy, cz,
                        short_x, RAD_NATIVE[2], RAD_LONG, "RadiatorGlossy")
    sx = RAD_LONG / RAD_NATIVE[0]                 # native X → world Z (long)
    sy = short_x / RAD_NATIVE[1]                  # native Y → world X (short)
    return (
        f'def Xform "{name}" (\n'
        f'    instanceable = true\n'
        f'    prepend references = </World/Satellite/_Protos/RadiatorPanel>\n'
        f')\n'
        f'{{\n'
        f'    double3 xformOp:translate = ({cx:.4f}, {cy:.4f}, {cz:.4f})\n'
        f'    float xformOp:rotateX = 90\n'
        f'    float xformOp:rotateZ = 90\n'
        f'    double3 xformOp:scale = ({sx:.4f}, {sy:.4f}, 1.0)\n'
        f'    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateX", "xformOp:rotateZ", "xformOp:scale"]\n'
        f'}}'
    )


def _radiator_mount_z() -> float:
    """Where the radiator booms leave the hull along ±Z, per architecture."""
    if ARCHITECTURE == "twin_truss":
        return 2.0 * SPINE_END_Z       # two stacked segments span ±1.0
    if ARCHITECTURE == "lumid":
        return LUMID_RAD_Z
    if ARCHITECTURE == "dish":
        return DISH_RAD_Z
    if ARCHITECTURE == "redwire":
        return REDWIRE_RAD_Z
    return SPINE_END_Z


def radiator_group() -> str:
    """A boom off each ±Z hull end with one long radiator beyond it — the
    radiator's short edge meets the boom tip, the long axis runs out along Z."""
    parts = []
    mount = _radiator_mount_z()
    for tag, dirn in (("Top", 1.0), ("Bot", -1.0)):
        end_z = mount * dirn
        boom_far = end_z + dirn * RAD_BOOM_LEN
        parts.append(box_mesh(f"RadBoom{tag}", RAD_X, 0.0, (end_z + boom_far) / 2.0,
                              RAD_BOOM_THICK, RAD_BOOM_THICK, RAD_BOOM_LEN, "SolarFrame"))
        parts.append(radiator_panel(f"Radiator{tag}", RAD_X, 0.0,
                                    boom_far + dirn * RAD_LONG / 2.0))
    body = "\n".join(parts)
    return f'def Xform "RadiatorArray"\n{{\n{indent(body, "    ")}\n}}'


def uv_sphere(name: str, center: tuple[float, float, float], radius: float,
              material: str, stacks: int = 36, slices: int = 72,
              double_sided: bool = False) -> str:
    """An equirectangular-UV sphere Mesh (lon→u, lat→v) so a lon/lat texture
    maps cleanly and every renderer draws it as real geometry."""
    cx, cy, cz = center
    pts, sts = [], []
    for j in range(stacks + 1):
        phi = -math.pi / 2 + math.pi * j / stacks
        cphi, sphi = math.cos(phi), math.sin(phi)
        for i in range(slices + 1):
            th = 2 * math.pi * i / slices
            pts.append((cx + radius * cphi * math.cos(th),
                        cy + radius * cphi * math.sin(th),
                        cz + radius * sphi))
            sts.append((i / slices, j / stacks))
    row = slices + 1
    idx, counts = [], []
    for j in range(stacks):
        for i in range(slices):
            a = j * row + i
            idx += [a, a + 1, a + row + 1, a + row]
            counts.append(4)
    pstr = ", ".join(f"({p[0]:.2f}, {p[1]:.2f}, {p[2]:.2f})" for p in pts)
    ststr = ", ".join(f"({s[0]:.4f}, {s[1]:.4f})" for s in sts)
    return (
        f'def Mesh "{name}" (\n'
        f'    prepend apiSchemas = ["MaterialBindingAPI"]\n'
        f')\n'
        f'{{\n'
        f'    float3[] extent = [({cx-radius:.1f}, {cy-radius:.1f}, {cz-radius:.1f}), '
        f'({cx+radius:.1f}, {cy+radius:.1f}, {cz+radius:.1f})]\n'
        f'    int[] faceVertexCounts = [{", ".join(map(str, counts))}]\n'
        f'    int[] faceVertexIndices = [{", ".join(map(str, idx))}]\n'
        f'    point3f[] points = [{pstr}]\n'
        f'    texCoord2f[] primvars:st = [{ststr}] (interpolation = "vertex")\n'
        f'    uniform token subdivisionScheme = "none"\n'
        f'    uniform bool doubleSided = {1 if double_sided else 0}\n'
        f'    rel material:binding = </World/Looks/{material}>\n'
        f'}}'
    )


def celestial_group() -> str:
    """Earth (plain day texture) + the HDR-emissive Sun. Siblings of the ×180
    Satellite, in absolute cm, so they hold realistic angular scale + position
    and sweep as the camera orbits.

    Both are ANIMATABLE Xforms (meshes authored around the local origin, the
    placement in xformOps) so the Kit scene extension can drive the orbital
    motion per frame: the Earth's rotateY/rotateZ pair aims the current
    sub-satellite point (lat, lon) at the satellite — rotateY(lat−90)·
    rotateZ(−lon) maps P(lat,lon) to local +Z, which faces the satellite from
    EARTH_CENTER — and the Sun's translate sweeps the visible disk along the
    zenith→sun angle. Static defaults below match the historical fixed pose,
    so the stage renders identically until the extension starts driving it."""
    earth_mesh = uv_sphere("Sphere", (0.0, 0.0, 0.0), EARTH_RADIUS_CM, "EarthMat", 48, 96)
    cloud_mesh = uv_sphere("Clouds", (0.0, 0.0, 0.0),
                           EARTH_RADIUS_CM * CLOUD_SCALE, "CloudMat", 48, 96)
    earth = (
        f'def Xform "Earth"\n'
        f'{{\n'
        f'    double3 xformOp:translate = ({EARTH_CENTER[0]:.1f}, {EARTH_CENTER[1]:.1f}, {EARTH_CENTER[2]:.1f})\n'
        f'    float xformOp:rotateY = -90\n'
        f'    float xformOp:rotateZ = 0\n'
        f'    uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateY", "xformOp:rotateZ"]\n'
        f'\n'
        f'{indent(earth_mesh, "    ")}\n'
        f'\n'
        f'{indent(cloud_mesh, "    ")}\n'
        f'}}'
    )
    sun_c = tuple(SUN_DIR[i] * SUN_DIST_CM for i in range(3))
    sun_mesh = uv_sphere("Sphere", (0.0, 0.0, 0.0), SUN_RADIUS_CM, "SunMat", 20, 32)
    sun = (
        f'def Xform "Sun"\n'
        f'{{\n'
        f'    double3 xformOp:translate = ({sun_c[0]:.1f}, {sun_c[1]:.1f}, {sun_c[2]:.1f})\n'
        f'    uniform token[] xformOpOrder = ["xformOp:translate"]\n'
        f'\n'
        f'{indent(sun_mesh, "    ")}\n'
        f'}}'
    )
    body = "\n".join([earth, sun])
    return f'def Xform "Celestial"\n{{\n{indent(body, "    ")}\n}}'


def backbone_override() -> str:
    """Clean every backbone material to shiny metal: constant clean diffuse,
    high metallic, low roughness, and block the grungy texture connections."""
    d = BACKBONE_DIFFUSE
    mats = []
    for m in BACKBONE_MATS:
        mats.append(
            f'over "{m}"\n'
            f'{{\n'
            f'    over "Principled_BSDF"\n'
            f'    {{\n'
            f'        color3f inputs:diffuseColor = ({d[0]:.3f}, {d[1]:.3f}, {d[2]:.3f})\n'
            f'        color3f inputs:diffuseColor.connect = None\n'
            f'        float inputs:metallic = {BACKBONE_METALLIC}\n'
            f'        float inputs:metallic.connect = None\n'
            f'        float inputs:roughness = {BACKBONE_ROUGHNESS}\n'
            f'        float inputs:roughness.connect = None\n'
            f'    }}\n'
            f'}}'
        )
    return f'over "_materials"\n{{\n{indent(chr(10).join(mats), "    ")}\n}}'


def _backbone_prim(name: str = "Backbone", z_off: float = 0.0) -> str:
    xform = ""
    if z_off:
        xform = (f'    double3 xformOp:translate = (0, 0, {z_off:.4f})\n'
                 f'    uniform token[] xformOpOrder = ["xformOp:translate"]\n')
    return (
        f'def Xform "{name}" (\n'
        f'    prepend references = @{BACKBONE_REF}@\n'
        f')\n'
        f'{{\n'
        f'{xform}'
        f'{indent(backbone_override(), "    ")}\n'
        f'}}'
    )


def _hull_prim(ref: str, native_size: float, target_u: float,
               native_center: tuple[float, float, float],
               rotate_z: float = 0.0) -> str:
    """A complete-satellite hull asset (LUMID / dish), uniformly scaled so its
    largest native dimension spans `target_u` backbone units and RECENTERED
    on the satellite origin (the assets' pivots sit far from their bbox
    centers). Ops apply scale, then rotateZ, then translate; the translate is
    −R(θ)·(s·center) so the bbox center lands exactly at the origin. These
    usdc hulls carry their own Looks scopes, so no material overrides."""
    s = target_u / native_size
    cx, cy, cz = (s * c for c in native_center)
    if rotate_z == 180.0:
        cx, cy = -cx, -cy
    elif rotate_z == 90.0:
        cx, cy = -cy, cx
    tx, ty, tz = -cx, -cy, -cz
    rot = f'    float xformOp:rotateZ = {rotate_z}\n' if rotate_z else ''
    order = ('["xformOp:translate", "xformOp:rotateZ", "xformOp:scale"]' if rotate_z
             else '["xformOp:translate", "xformOp:scale"]')
    return (
        f'def Xform "Hull" (\n'
        f'    prepend references = @{ref}@\n'
        f')\n'
        f'{{\n'
        f'    double3 xformOp:translate = ({tx:.4f}, {ty:.4f}, {tz:.4f})\n'
        f'{rot}'
        f'    double3 xformOp:scale = ({s:.6f}, {s:.6f}, {s:.6f})\n'
        f'    uniform token[] xformOpOrder = {order}\n'
        f'}}'
    )


def _architecture_parts() -> list[str]:
    """The hull + payload prims for the active ARCHITECTURE (everything under
    /World/Satellite except the shared prototypes)."""
    if ARCHITECTURE == "twin_truss":
        return [
            _backbone_prim("BackboneUp", +SPINE_END_Z),
            _backbone_prim("BackboneDown", -SPINE_END_Z),
            servers_group(+SPINE_END_Z, "U"),
            servers_group(-SPINE_END_Z, "D"),
            solar_group(),
            radiator_group(),
        ]
    if ARCHITECTURE == "lumid":
        return [
            _hull_prim(LUMID_REF, LUMID_NATIVE_Z, LUMID_TARGET_U,
                       LUMID_NATIVE_CENTER),
            radiator_group(),
        ]
    if ARCHITECTURE == "dish":
        # rotateZ=180 turns the dish boresight to -X: the +X face belongs to
        # the sun-tracking cells, the dish looks back at Earth's horizon.
        return [
            _hull_prim(DISH_REF, DISH_NATIVE_YZ, DISH_TARGET_U,
                       DISH_NATIVE_CENTER, rotate_z=180.0),
            radiator_group(),
        ]
    if ARCHITECTURE == "redwire":
        # Compact flat payload bay; rotateZ=90 turns the bay's row of
        # DISCRETE GPU MODULES (the asset's own front-edge units — the
        # popup maps them to the GPU panel) to the +X sun/camera face,
        # flat deck-parallel wings bolt onto the ±Y edge lugs, radiators
        # boom off the ±Z deck faces.
        return [
            _hull_prim(REDWIRE_REF, REDWIRE_NATIVE, REDWIRE_TARGET_U,
                       REDWIRE_NATIVE_CENTER, rotate_z=90.0),
            solar_group(),
            radiator_group(),
        ]
    # truss + blanket share the single-spine hull.
    return [
        _backbone_prim(),
        servers_group(),
        solar_group(),
        radiator_group(),
    ]


def satellite_prim() -> str:
    parts = _architecture_parts()
    if not PREVIEW_LITE:
        # Shared instancing prototypes for the heavy scanned deployables —
        # must sit under /World/Satellite so instances inherit the ×180 frame.
        # Hull architectures only instance the radiator panels.
        parts.insert(0, deployable_prototypes(
            include_solar=ARCHITECTURE not in ("lumid", "dish")))
    inner = "\n\n".join(parts)
    return f"""def Xform "Satellite"
{{
    double3 xformOp:scale = ({BACKBONE_SCALE}, {BACKBONE_SCALE}, {BACKBONE_SCALE})
    uniform token[] xformOpOrder = ["xformOp:scale"]

{indent(inner, "    ")}
}}"""


def _frame_radius_cm() -> float:
    """Largest deployed extent (solar tip along Y, radiator tip along Z) in cm,
    so the camera distance scales with whatever geometry is configured."""
    deploy = SOLAR_NATIVE[1] * PANEL_SCALE[1]
    if ARCHITECTURE == "blanket":
        solar_tip = (BOOM_Y1 + N_PANELS * 2.0 * deploy) * BACKBONE_SCALE
    elif ARCHITECTURE in ("lumid", "dish"):
        hull_u = LUMID_TARGET_U if ARCHITECTURE == "lumid" else DISH_TARGET_U
        solar_tip = (hull_u / 2.0) * BACKBONE_SCALE
    elif ARCHITECTURE == "redwire":
        # Flat wings chain outward by their D span, straight off the deck edge.
        solar_tip = (REDWIRE_WING_Y0 + N_PANELS * deploy) * BACKBONE_SCALE
    else:
        solar_tip = (BOOM_Y1 + N_PANELS * deploy) * BACKBONE_SCALE
    rad_tip = (_radiator_mount_z() + RAD_BOOM_LEN + RAD_LONG) * BACKBONE_SCALE
    return max(solar_tip, rad_tip)


def cameras_scope() -> str:
    """Closeup camera — a far 3/4 view (CAM_EYE direction) auto-pulled back to
    the configured frame radius, so any solar count / radiator size stays in
    frame after a regenerate."""
    dn = math.sqrt(sum(c * c for c in CAM_EYE)) or 1.0
    dist = _frame_radius_cm() * 5.5
    eye = tuple(c / dn * dist for c in CAM_EYE)
    target = (0.0, 0.0, 0.0)
    fx, fy, fz = (target[i] - eye[i] for i in range(3))
    fn = math.sqrt(fx*fx + fy*fy + fz*fz) or 1.0
    fx, fy, fz = fx/fn, fy/fn, fz/fn
    wux, wuy, wuz = 0.0, 0.0, 1.0
    rx, ry, rz = fy*wuz - fz*wuy, fz*wux - fx*wuz, fx*wuy - fy*wux
    rn = math.sqrt(rx*rx + ry*ry + rz*rz) or 1.0
    rx, ry, rz = rx/rn, ry/rn, rz/rn
    ux, uy, uz = ry*fz - rz*fy, rz*fx - rx*fz, rx*fy - ry*fx
    rows = [
        (rx, ry, rz, 0.0),
        (ux, uy, uz, 0.0),
        (-fx, -fy, -fz, 0.0),
        (eye[0], eye[1], eye[2], 1.0),
    ]
    rows_text = ",\n                ".join(
        f"({r[0]:.5f}, {r[1]:.5f}, {r[2]:.5f}, {r[3]:.5f})" for r in rows
    )
    focus = math.sqrt(sum((eye[i]-target[i])**2 for i in range(3)))
    return f"""def Xform "Cameras"
{{
    def Camera "Closeup"
    {{
        float focalLength = {CAM_FOCAL:.1f}
        float focusDistance = {focus:.0f}
        float2 clippingRange = (1, 90000)
        matrix4d xformOp:transform = (
                {rows_text}
        )
        uniform token[] xformOpOrder = ["xformOp:transform"]
    }}
}}"""


def build_usda() -> str:
    parts = [
        '#usda 1.0',
        '(',
        '    defaultPrim = "World"',
        '    upAxis = "Z"',
        '    metersPerUnit = 0.01',
        '    doc = "Twin satellite — SpaceDcBackbone.usdz spine: a compute-server blade in each of the 12 rack slots, plus two oversized solar wings on booms off the central deployment brackets. Generated by tools/gen_twin_satellite.py."',
        ')',
        '',
        'def Xform "World"',
        '{',
        indent(looks_scope(), '    '),
        '',
        indent(satellite_prim(), '    '),
        '',
        indent(celestial_group(), '    '),
        '',
        indent(cameras_scope(), '    '),
        '}',
        '',
    ]
    return "\n".join(parts)


def _load_params(params_path: Path | None = None) -> dict:
    """Optional runtime geometry overrides written by the backend
    (usd/twin_params.json, or an explicit --params file): keys
    solar_clusters_per_side, radiator_long, radiator_ratio, use_dgx.
    Absent file → built-in defaults."""
    import json
    pf = params_path if params_path is not None else ROOT / "usd" / "twin_params.json"
    if pf.exists():
        try:
            return json.loads(pf.read_text(encoding="utf-8"))
        except Exception as e:  # noqa: BLE001 — never let a bad file break gen
            print(f"[gen] WARN ignoring bad {pf.name}: {e}")
    return {}


def _parse_cli(argv: list[str]) -> tuple[Path | None, Path]:
    """--params <json> reads geometry from an alternate file (the live
    twin_params.json stays untouched); --out <usda> writes the stage
    somewhere other than usd/twin_satellite.usda. Both optional — the
    no-arg invocation is byte-identical to the historical behaviour.
    The backend uses the pair to build per-design preview stages."""
    params_path: Path | None = None
    out_path = OUT
    i = 0
    while i < len(argv):
        if argv[i] == "--params" and i + 1 < len(argv):
            params_path = Path(argv[i + 1]); i += 2
        elif argv[i] == "--out" and i + 1 < len(argv):
            out_path = Path(argv[i + 1]); i += 2
        else:
            raise SystemExit(f"[gen] unknown arg {argv[i]!r} "
                             "(usage: gen_twin_satellite.py [--params p.json] [--out stage.usda])")
    return params_path, out_path


def main(argv: list[str] | None = None) -> None:
    global N_PANELS, RAD_LONG, RAD_RATIO, USE_DGX, PREVIEW_LITE, ARCHITECTURE
    import sys
    params_path, out_path = _parse_cli(sys.argv[1:] if argv is None else argv)
    p = _load_params(params_path)
    N_PANELS  = max(1, min(8, int(p.get("solar_clusters_per_side", N_PANELS))))
    RAD_LONG  = max(0.3, min(3.0, float(p.get("radiator_long", RAD_LONG))))
    RAD_RATIO = max(1.2, min(6.0, float(p.get("radiator_ratio", RAD_RATIO))))
    arch = str(p.get("architecture", ARCHITECTURE))
    ARCHITECTURE = arch if arch in ARCHITECTURES else "truss"
    # Previews render with the lightweight procedural blades — the DGX asset
    # is ~150 MB and only worth composing in the live Kit stage.
    USE_DGX = bool(p.get("use_dgx", USE_DGX))
    PREVIEW_LITE = bool(p.get("preview_lite", PREVIEW_LITE))
    if p:
        print(f"[gen] params: arch={ARCHITECTURE} solar/side={N_PANELS} "
              f"rad_long={RAD_LONG} rad_ratio={RAD_RATIO} "
              f"dgx={USE_DGX} lite={PREVIEW_LITE}")
    out = build_usda()
    # Atomic publish: Kit force-reloads this layer the moment the backend
    # bumps the geometry version, and an unrelated earlier reload could also
    # land mid-write — never let a reader see a half-written stage.
    import os
    tmp_path = out_path.with_name(out_path.name + ".tmp")
    tmp_path.write_text(out, encoding="utf-8")
    os.replace(tmp_path, out_path)
    print(f"[gen] wrote {out_path} ({len(out):,} bytes)")


if __name__ == "__main__":
    main()
