"""Generate usd/mission.usda — the 天数天算 mission "hero stage".

A clean cinematic set (no Earth, no orbit rings): deep black space + a
starfield, dramatic 3-point lighting, the two task satellites, and the
props the space.demo.scene extension animates per phase —

  * ScanBeam      — a cone projecting from the sensor sat (image capture)
  * Packets/Cube_NN — a pool of small cubes; the data is shown as discrete
                      packet blocks flowing along the route (NOT a laser)
  * ComputeCore/Card_NN — a little server rack beside the hub that flickers
                      while it runs inference (GPU activity)
  * GroundStation — a dish the downlink result is delivered to; the camera
                      follows the packets down to it

Layout (metersPerUnit = 1, units = metres):
    SensorSat (-9,0,0)  HubSat (9,1.5,2)  GroundStation (-3,-10,-32)

Run:
    python tools/gen_mission_stage.py
"""
from __future__ import annotations

import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT / "usd" / "mission.usda"

SAT_REF = "./assets/Satellite_v022.usdc"
SAT_SCALE = 0.024
SENSOR_POS = (-9.0, 0.0, 0.0)
HUB_POS    = (9.0, 1.5, 2.0)
GROUND_POS = (-3.0, -10.0, -32.0)

# The imaged scene — NVIDIA AEC City Tower pack. Z-up, cm units; the tower
# is ~155 m (~15503 units). Scaled to ~15 m tall and parked below the
# sensor; the driver sweeps the camera over it during capture, then
# collapses it into a data cube that flies up to the sensor.
CITY_REF   = "./aeco_city/Demos/AEC/TowerDemo/CityTowerDemopack/World_CityTowerDemopack.usd"
CITY_POS   = (0.0, 6.0, -24.0)
CITY_SCALE = 0.0011

PACKET_CUBES = 8     # pool size for the data-block stream
GPU_CARDS    = 8     # server-rack cards beside the hub

STAR_COUNT = 700
STAR_RADIUS = 500.0
STAR_SEED = 0xA11CE


def _stars() -> tuple[list, list]:
    rng = random.Random(STAR_SEED)
    pts, widths = [], []
    for _ in range(STAR_COUNT):
        z = rng.uniform(-1.0, 1.0)
        t = rng.uniform(0.0, 2.0 * math.pi)
        r = math.sqrt(max(0.0, 1.0 - z * z))
        x, y = r * math.cos(t), r * math.sin(t)
        pts.append((x * STAR_RADIUS, y * STAR_RADIUS, z * STAR_RADIUS))
        widths.append(round(rng.uniform(0.6, 2.4), 2))
    return pts, widths


def _vec_list(pts) -> str:
    return ", ".join(f"({p[0]:.2f}, {p[1]:.2f}, {p[2]:.2f})" for p in pts)


def _float_list(vs) -> str:
    return ", ".join(f"{v}" for v in vs)


def _packet_cubes() -> str:
    """A pool of small cube prims; the driver positions + shows them to make
    the data-packet stream. Start invisible at the sensor."""
    sx, sy, sz = SENSOR_POS
    out = []
    for i in range(PACKET_CUBES):
        out.append(f"""
        def Cube "Cube_{i:02d}" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            double size = 2.0
            double3 xformOp:translate = ({sx}, {sy}, {sz})
            double3 xformOp:scale = (0.32, 0.32, 0.32)
            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
            token visibility = "invisible"
            uniform bool primvars:doNotCastShadows = 1
            rel material:binding = </World/Looks/PacketMat>
        }}""")
    return "".join(out)


def _gpu_cards() -> str:
    """A 2×4 grid of thin cards just in front of the hub — the DGX rack.
    Driver flickers their visibility during compute. Positioned relative to
    the hub; start invisible."""
    hx, hy, hz = HUB_POS
    out = []
    cols, rows = 4, 2
    cw, ch, gap = 0.55, 0.5, 0.25
    span_x = cols * cw + (cols - 1) * gap
    span_z = rows * ch + (rows - 1) * gap
    for r in range(rows):
        for c in range(cols):
            i = r * cols + c
            cx = hx - 3.5 + (c * (cw + gap)) - span_x / 2 + cw / 2
            cz = hz + (r * (ch + gap)) - span_z / 2 + ch / 2
            cy = hy - 2.0
            out.append(f"""
        def Cube "Card_{i:02d}" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            double size = 2.0
            double3 xformOp:translate = ({cx:.2f}, {cy:.2f}, {cz:.2f})
            double3 xformOp:scale = ({cw/2:.2f}, 0.08, {ch/2:.2f})
            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
            token visibility = "invisible"
            uniform bool primvars:doNotCastShadows = 1
            rel material:binding = </World/Looks/GpuMat>
        }}""")
    return "".join(out)


def build() -> str:
    star_pts, star_w = _stars()
    sx, sy, sz = SENSOR_POS
    hx, hy, hz = HUB_POS
    gx, gy, gz = GROUND_POS
    s = SAT_SCALE

    return f"""#usda 1.0
(
    defaultPrim = "World"
    upAxis = "Z"
    metersPerUnit = 1.0
    doc = "天数天算 mission hero stage — black space + stars + dramatic lighting + the two task sats, a sensor scan beam, a packet-cube stream, a hub GPU rack, and a ground station. No Earth / no orbit rings. Driven by space.demo.scene. Generated by tools/gen_mission_stage.py."
    customLayerData = {{
        dictionary cameraSettings = {{
            string boundCamera = "/World/Cameras/MissionHero"
        }}
    }}
)

def Xform "World"
{{
    def Xform "Environment"
    {{
        def DistantLight "Key"
        {{
            float inputs:angle = 1.0
            float inputs:intensity = 4200
            color3f inputs:color = (1.0, 0.95, 0.88)
            float3 xformOp:rotateXYZ = (-40, 0, 35)
            uniform token[] xformOpOrder = ["xformOp:rotateXYZ"]
        }}
        def DistantLight "Rim"
        {{
            float inputs:angle = 0.6
            float inputs:intensity = 3600
            color3f inputs:color = (0.45, 0.62, 1.0)
            float3 xformOp:rotateXYZ = (25, 0, -150)
            uniform token[] xformOpOrder = ["xformOp:rotateXYZ"]
        }}
        def DomeLight "Space"
        {{
            color3f inputs:color = (0.02, 0.03, 0.06)
            float inputs:intensity = 14.0
            token inputs:texture:format = "latlong"
        }}
    }}

    def Scope "Looks"
    {{
        def Material "StarMat"
        {{
            token outputs:surface.connect = </World/Looks/StarMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:emissiveColor = (1.4, 1.45, 1.6)
                float inputs:roughness = 1.0
                token outputs:surface
            }}
        }}
        def Material "PacketMat"
        {{
            token outputs:surface.connect = </World/Looks/PacketMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0.05, 0.30, 0.45)
                color3f inputs:emissiveColor = (0.30, 1.90, 2.60)
                float inputs:roughness = 0.4
                token outputs:surface
            }}
        }}
        def Material "GpuMat"
        {{
            token outputs:surface.connect = </World/Looks/GpuMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0.92, 0.94, 0.96)
                color3f inputs:emissiveColor = (0.04, 0.045, 0.05)
                float inputs:metallic = 1.0
                float inputs:roughness = 0.12
                int inputs:useSpecularWorkflow = 0
                token outputs:surface
            }}
        }}
        def Material "ScanMat"
        {{
            token outputs:surface.connect = </World/Looks/ScanMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:emissiveColor = (0.25, 1.40, 2.20)
                float inputs:opacity = 0.22
                float inputs:roughness = 1.0
                token outputs:surface
            }}
        }}
        def Material "StationMat"
        {{
            token outputs:surface.connect = </World/Looks/StationMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0.62, 0.66, 0.72)
                float inputs:metallic = 0.8
                float inputs:roughness = 0.35
                token outputs:surface
            }}
        }}
        def Material "DishMat"
        {{
            token outputs:surface.connect = </World/Looks/DishMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0.85, 0.87, 0.90)
                color3f inputs:emissiveColor = (0.10, 0.30, 0.20)
                float inputs:metallic = 0.6
                float inputs:roughness = 0.3
                token outputs:surface
            }}
        }}
    }}

    def Points "Stars" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        point3f[] points = [{_vec_list(star_pts)}]
        float[] widths = [{_float_list(star_w)}] (interpolation = "vertex")
        uniform bool primvars:doNotCastShadows = 1
        rel material:binding = </World/Looks/StarMat>
    }}

    def Xform "SensorSat" (
        prepend references = @{SAT_REF}@
    )
    {{
        double3 xformOp:translate = ({sx}, {sy}, {sz})
        float3 xformOp:rotateXYZ = (0, 0, 20)
        double3 xformOp:scale = ({s}, {s}, {s})
        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
    }}

    def Xform "HubSat" (
        prepend references = @{SAT_REF}@
    )
    {{
        double3 xformOp:translate = ({hx}, {hy}, {hz})
        float3 xformOp:rotateXYZ = (0, 0, -160)
        double3 xformOp:scale = ({s}, {s}, {s})
        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
    }}

    # The imaged scene — AEC City Tower pack. Shown during acquire/capture;
    # the driver sweeps the camera over it then collapses its scale to ~0.
    def Xform "TargetScene" (
        prepend references = @{CITY_REF}@
    )
    {{
        double3 xformOp:translate = ({CITY_POS[0]}, {CITY_POS[1]}, {CITY_POS[2]})
        double3 xformOp:scale = ({CITY_SCALE}, {CITY_SCALE}, {CITY_SCALE})
        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
        token visibility = "invisible"
    }}

    # The "captured data" block — appears as the scene collapses, then flies
    # up to the sensor. Driven by the extension.
    def Cube "CaptureCube" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        double size = 2.0
        double3 xformOp:translate = ({CITY_POS[0]}, {CITY_POS[1]}, {CITY_POS[2]})
        double3 xformOp:scale = (0.5, 0.5, 0.5)
        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:scale"]
        token visibility = "invisible"
        uniform bool primvars:doNotCastShadows = 1
        rel material:binding = </World/Looks/PacketMat>
    }}

    def Xform "Packets"
    {{{_packet_cubes()}
    }}

    def Xform "ComputeCore"
    {{{_gpu_cards()}
    }}

    # Ground station — mast + dish, the downlink delivery target.
    def Xform "GroundStation"
    {{
        double3 xformOp:translate = ({gx}, {gy}, {gz})
        uniform token[] xformOpOrder = ["xformOp:translate"]

        def Cylinder "Base" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            double height = 0.6
            double radius = 1.6
            uniform token axis = "Z"
            double3 xformOp:translate = (0, 0, 0.3)
            uniform token[] xformOpOrder = ["xformOp:translate"]
            rel material:binding = </World/Looks/StationMat>
        }}
        def Cylinder "Mast" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            double height = 2.4
            double radius = 0.28
            uniform token axis = "Z"
            double3 xformOp:translate = (0, 0, 1.8)
            uniform token[] xformOpOrder = ["xformOp:translate"]
            rel material:binding = </World/Looks/StationMat>
        }}
        # Dish — a shallow cone tilted up toward the satellites.
        def Cone "Dish" (
            prepend apiSchemas = ["MaterialBindingAPI"]
        )
        {{
            double height = 0.7
            double radius = 2.0
            uniform token axis = "Z"
            double3 xformOp:translate = (0, 0, 3.2)
            float3 xformOp:rotateXYZ = (35, 0, 0)
            uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ"]
            rel material:binding = </World/Looks/DishMat>
        }}
    }}

    def Xform "Cameras"
    {{
        def Camera "MissionHero"
        {{
            float focalLength = 35.0
            float focusDistance = 30
            float2 clippingRange = (0.1, 3000)
            matrix4d xformOp:transform = (
                (1, 0, 0, 0),
                (0, 0.7, 0.71, 0),
                (0, -0.71, 0.7, 0),
                (0, -28, 12, 1)
            )
            uniform token[] xformOpOrder = ["xformOp:transform"]
        }}
    }}
}}
"""


def main() -> None:
    out = build()
    OUT.write_text(out, encoding="utf-8")
    print(f"[gen] wrote {OUT} ({len(out):,} bytes, {STAR_COUNT} stars, "
          f"{PACKET_CUBES} packet cubes, {GPU_CARDS} GPU cards)")


if __name__ == "__main__":
    main()
