"""Generate usd/mission.usda — the 天数天算 mission "hero stage".

A clean cinematic set, deliberately NOT the geo overview: no Earth, no
orbit rings. Just deep black space + a starfield, dramatic 3-point
lighting, and the two task satellites (Satellite_v022 body) staged for a
beauty shot. The space.demo.scene extension drives the data packet, the
ISL / result beams, satellite visibility, and the follow-cam per mission
phase.

Layout (metersPerUnit = 1, units = metres):
    /World
        /Environment   Key + Rim + Fill lights (rim-lit sats on black)
        /Stars         ~700 procedural star points on a 500 m sphere
        /SensorSat     Satellite_v022 @ (-9, 0, 0)
        /HubSat        Satellite_v022 @ (9, 1.5, 2)
        /Packet        glowing data blob (driven)
        /ISLBeam       sensor → hub (driven)
        /ResultBeam    hub → camera/off-frame for downlink (driven)
        /Looks         emissive materials
        /Cameras/MissionHero   driven by the extension

Run:
    python tools/gen_mission_stage.py
"""
from __future__ import annotations

import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT  = ROOT / "usd" / "mission.usda"

SAT_REF = "./assets/Satellite_v022.usdc"
SAT_SCALE = 0.024          # v022 raw ~168 → ~4 m
SENSOR_POS = (-9.0, 0.0, 0.0)
HUB_POS    = (9.0, 1.5, 2.0)

STAR_COUNT = 700
STAR_RADIUS = 500.0
STAR_SEED = 0xA11CE


def _stars() -> tuple[list, list]:
    rng = random.Random(STAR_SEED)
    pts, widths = [], []
    for _ in range(STAR_COUNT):
        # Uniform on sphere.
        z = rng.uniform(-1.0, 1.0)
        t = rng.uniform(0.0, 2.0 * math.pi)
        r = math.sqrt(max(0.0, 1.0 - z * z))
        x, y = r * math.cos(t), r * math.sin(t)
        pts.append((x * STAR_RADIUS, y * STAR_RADIUS, z * STAR_RADIUS))
        widths.append(round(rng.uniform(0.6, 2.4), 2))
    return pts, widths


def _vec_list(pts) -> str:
    return ", ".join(f"({p[0]:.2f}, {p[1]:.2f}, {p[2]:.2f})" for p in pts)


def _float_list(vs) -> str:
    return ", ".join(f"{v}" for v in vs)


def build() -> str:
    star_pts, star_w = _stars()
    sx, sy, sz = SENSOR_POS
    hx, hy, hz = HUB_POS
    s = SAT_SCALE

    return f"""#usda 1.0
(
    defaultPrim = "World"
    upAxis = "Z"
    metersPerUnit = 1.0
    doc = "天数天算 mission hero stage — black space + stars + dramatic lighting + the two task sats. No Earth / no orbit rings; the space.demo.scene extension drives the packet, beams, and follow-cam. Generated by tools/gen_mission_stage.py."
    customLayerData = {{
        dictionary cameraSettings = {{
            string boundCamera = "/World/Cameras/MissionHero"
        }}
    }}
)

def Xform "World"
{{
    def Xform "Environment"
    {{
        # Warm key from upper front-right.
        def DistantLight "Key"
        {{
            float inputs:angle = 1.0
            float inputs:intensity = 4200
            color3f inputs:color = (1.0, 0.95, 0.88)
            float3 xformOp:rotateXYZ = (-40, 0, 35)
            uniform token[] xformOpOrder = ["xformOp:rotateXYZ"]
        }}
        # Cool rim from behind to edge-light the sats against black.
        def DistantLight "Rim"
        {{
            float inputs:angle = 0.6
            float inputs:intensity = 3600
            color3f inputs:color = (0.45, 0.62, 1.0)
            float3 xformOp:rotateXYZ = (25, 0, -150)
            uniform token[] xformOpOrder = ["xformOp:rotateXYZ"]
        }}
        # Near-black deep-space ambient so shadows aren't pure void.
        def DomeLight "Space"
        {{
            color3f inputs:color = (0.02, 0.03, 0.06)
            float inputs:intensity = 14.0
            token inputs:texture:format = "latlong"
        }}
    }}

    def Scope "Looks"
    {{
        def Material "StarMat"
        {{
            token outputs:surface.connect = </World/Looks/StarMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0, 0, 0)
                color3f inputs:emissiveColor = (1.4, 1.45, 1.6)
                float inputs:roughness = 1.0
                token outputs:surface
            }}
        }}
        def Material "PacketMat"
        {{
            token outputs:surface.connect = </World/Looks/PacketMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0, 0, 0)
                color3f inputs:emissiveColor = (0.30, 2.20, 2.80)
                float inputs:roughness = 1.0
                token outputs:surface
            }}
        }}
        def Material "ISLMat"
        {{
            token outputs:surface.connect = </World/Looks/ISLMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0, 0, 0)
                color3f inputs:emissiveColor = (0.20, 1.60, 2.60)
                float inputs:roughness = 1.0
                token outputs:surface
            }}
        }}
        def Material "ResultMat"
        {{
            token outputs:surface.connect = </World/Looks/ResultMat/Shader.outputs:surface>
            def Shader "Shader"
            {{
                uniform token info:id = "UsdPreviewSurface"
                color3f inputs:diffuseColor = (0, 0, 0)
                color3f inputs:emissiveColor = (0.40, 2.20, 0.80)
                float inputs:roughness = 1.0
                token outputs:surface
            }}
        }}
    }}

    def Points "Stars" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        point3f[] points = [{_vec_list(star_pts)}]
        float[] widths = [{_float_list(star_w)}] (interpolation = "vertex")
        uniform bool primvars:doNotCastShadows = 1
        rel material:binding = </World/Looks/StarMat>
    }}

    def Xform "SensorSat" (
        prepend references = @{SAT_REF}@
    )
    {{
        double3 xformOp:translate = ({sx}, {sy}, {sz})
        float3 xformOp:rotateXYZ = (0, 0, 20)
        double3 xformOp:scale = ({s}, {s}, {s})
        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
    }}

    def Xform "HubSat" (
        prepend references = @{SAT_REF}@
    )
    {{
        double3 xformOp:translate = ({hx}, {hy}, {hz})
        float3 xformOp:rotateXYZ = (0, 0, -160)
        double3 xformOp:scale = ({s}, {s}, {s})
        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]
    }}

    def Points "Packet" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        point3f[] points = [({sx}, {sy}, {sz})]
        float[] widths = [1.4] (interpolation = "vertex")
        uniform bool primvars:doNotCastShadows = 1
        token visibility = "invisible"
        rel material:binding = </World/Looks/PacketMat>
    }}

    def BasisCurves "ISLBeam" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        uniform token type = "linear"
        uniform token wrap = "nonperiodic"
        int[] curveVertexCounts = [2]
        point3f[] points = [({sx}, {sy}, {sz}), ({hx}, {hy}, {hz})]
        float[] widths = [0.35] (interpolation = "constant")
        uniform bool primvars:doNotCastShadows = 1
        token visibility = "invisible"
        rel material:binding = </World/Looks/ISLMat>
    }}

    def BasisCurves "ResultBeam" (
        prepend apiSchemas = ["MaterialBindingAPI"]
    )
    {{
        uniform token type = "linear"
        uniform token wrap = "nonperiodic"
        int[] curveVertexCounts = [2]
        point3f[] points = [({hx}, {hy}, {hz}), (0, -40, -20)]
        float[] widths = [0.3] (interpolation = "constant")
        uniform bool primvars:doNotCastShadows = 1
        token visibility = "invisible"
        rel material:binding = </World/Looks/ResultMat>
    }}

    def Xform "Cameras"
    {{
        def Camera "MissionHero"
        {{
            float focalLength = 35.0
            float focusDistance = 30
            float2 clippingRange = (0.1, 3000)
            matrix4d xformOp:transform = (
                (1, 0, 0, 0),
                (0, 0.7, 0.71, 0),
                (0, -0.71, 0.7, 0),
                (0, -28, 12, 1)
            )
            uniform token[] xformOpOrder = ["xformOp:transform"]
        }}
    }}
}}
"""


def main() -> None:
    out = build()
    OUT.write_text(out, encoding="utf-8")
    print(f"[gen] wrote {OUT} ({len(out):,} bytes, {STAR_COUNT} stars)")


if __name__ == "__main__":
    main()
