function initialize_reference
% Make the delivered SLX directly runnable after opening it in a fresh MATLAB.
here=fileparts(mfilename('fullpath'));suite=jsondecode(fileread(fullfile(here,'..','results','suite.json')));
cfg=struct('kind','dynamic','row',struct('G',1361,'cosine',1,'request',200,'T',293.15,...
    'connected',1,'latched',0,'current',0,'mode','allocate','command','none','bad','none'),...
    'p',reference_parameters(suite.parameters,struct()),...
    'x0',[suite.scene.initial_state.x_n;suite.scene.initial_state.x_p;293.15],...
    'thermal',false,'C',1,'R',1,'Tsink',293.15);
assignin('base','cfg',cfg);
if ~bdIsLoaded('sdtwin_power_reference'),return;end
set_param('sdtwin_power_reference','SolverType','Variable-step','Solver','ode45',...
    'RelTol','1e-8','AbsTol','1e-10','MaxStep','10','StartTime','0','StopTime','900',...
    'OutputOption','SpecifiedOutputTimes','OutputTimes','0:10:900');
end
